### ISSUE TITLE
PyTorch Model Support

### ISSUE THREAD

**Issue by franva** [luxonis/depthai-ml-training#12]
Hi team,

Just wondering do you have any plan for supporting the PyTorch models in the converter?

With such a popularity for PyTorch, it seems odd to not support PyTorch models.

I was okay to go with TF until I actually tried to train a custom model and received so many hurdles:

This is what I have experienced:

**Hurdle 1**
I followed the official tutorials for training a custom segmentation model [here](https://github.com/luxonis/depthai-ml-training/tree/master/colab-notebooks#tiny-yolov3-object-detector-training-) and [here](https://colab.research.google.com/github/luxonis/depthai-ml-training)
and found they are all DEPRECATED(ctrl+c, ctrl+v without changing the cap).  

**Hurdle 2**
I then followed the [Roboflow colab notebook](https://github.com/superannotateai/model-deployment-tutorials/blob/main/OAK/SuperAnnotate_OAK_Deeplabv3%2B_Deployment.ipynb), then discovered that we need to apply for a token in order to use its script, which I cannot find...

**Hurdle 3**
I then created an account on their website and found some api keys and tried each(e.g. Publishable API Key), but none of them worked. 

After hours searching, I gave up. it's just too much hustles to try to follow the tutorial to train our custom models with Tensorflow...

I then went to the blob converter website and found it does not even support PyTorch...

My suggestions:
1. customers have paid for the hardware, please provide them with open source project(not the deprecated one) for them to train their custom models free. Try to minimize the difficulties to use your products. 
2. My expectation was once I paid for the hardware, I do not need to pay anything else in order to use it without difficulties. But the reality is, sure Roboflow provides the "public version" which is free(but need token??? no where to find the token) to use, but we have to trade out our data set in order to use its service...  Could we try to clean up the old and deprecated code and provide your customers a clean, update to date and functional code and let them happily to use your products??
3. Hopefully, the PyTorch models can be supported soon.

**Comment by Erol444** [comment]
Hello @franva , deeplab semantic segmentation training demo PR is here: https://github.com/luxonis/depthai-ml-training/pull/11
