### ISSUE TITLE
Numpy mismatch with Easy_Object_Detection_With_Custom_Data_Demo_Training_Git.ipynb

### ISSUE THREAD

**Issue by stoecker** [luxonis/depthai-ml-training#18]
When running the Colab there is an error in stage "Install Tensorflow Object Detection API":

RuntimeError: module compiled against API version 0xe but this version of numpy is 0xd

I tried different solutions. When I install numpy 1.20.0 this stage works, but it fails later in the training.

This still worked about 3 weeks ago.

Can you fix it again?

**Comment by themarpe** [comment]
(CC: @tersekmatija - consider pinning pip / other dependencies, so that newer versions don't break existing workflows for no beneficial reasons)

**Comment by tersekmatija** [comment]
Hey @stoecker , could you try numpy==1.19.5?

(CC @conorsim on this notebook.)

**Comment by stoecker** [comment]
1.19.5 doesn't help. I still get the 0xd/0xe error in "Install Tensorflow Object Detection API". I have a print of the numpy version there and it outputs 1.19.5 as expected.

**Comment by conorsim** [comment]
Hey @stoecker, sorry you are having issues. Just to clarify, you are using numpy 1.17.5 and restarting the kernel after running that first cell, right?

If the error is happening on the training cell, it might actually be another one I am aware of. Working on updating this now.

**Comment by stoecker** [comment]
Yes. But is seems tensorflow (or a related component) now needs at least 1.20.0. When I switch to numpy 1.20.0, then get further, but it fails with a missing function later. I also tried downgrading tensorflow and also other components and also different other things, but I couldn't get a reliable state. Either this or that fails.

I don't fully understand all dependencies, so I'm more trying then fixing anything...

**Comment by conorsim** [comment]
Try keeping the numpy version in there and running this before the training cell:

`!pip uninstall pycocotools
!pip install --no-cache-dir pycocotools`

That's what is working for me.

**Comment by stoecker** [comment]
Yes. That helped. Thanks a lot. I used "!pip uninstall -y pycocotools" to prevent the interactive request.

A small note. I had trouble getting the ngrok stuff to run, so I added a few changes in "Train the model":
```
! killall ngrok
# get token here https://ngrok.com/
! ./ngrok authtoken ....
get_ipython().system_raw('./ngrok http 6006 &')
! sleep 3
```

* The killall alows multiple starts
* The authtoken line is for authentication, wont work without
* The system call is unchanged
* The sleep line ensure the next line works correctly always

I think they may be helpful for others too.

**Comment by conorsim** [comment]
Thanks @stoecker !

**Comment by themarpe** [comment]
(@conorsim as stated above, I advise you to pin pip / other dependencies, so that newer versions don't break existing workflows for no beneficial reasons as well as integrate the necessary changes across various workflows)

**Comment by conorsim** [comment]
Thanks @themarpe I pinned them.

**Comment by UcefMountacer** [comment]
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject

the solution also worked for this (with conserving the numpy version)
```
!pip uninstall pycocotools
!pip install --no-cache-dir pycocotools
```
