### ISSUE TITLE
tensorflow_version 2.x?

### ISSUE THREAD

**Issue by projectscjc** [luxonis/depthai-ml-training#24]
i can't seem to run TensorFlow 1.x with google cob so i changed the code to TensorFlow_ versions 2.x.   Now im getting this error contrib_training' is not defined error when trying to train

Could someone help me with my issue please

**Comment by Luxonis-Brandon** [comment]
Sorry about the trouble.  We'll be moving off of Colab as this sort of thing happens often.  

Could you share what type of model you are trying to train?  We can probably help directly outside of Colab.

Thanks, and sorry about the trouble!
-Brandon

**Comment by projectscjc** [comment]
Hi thanks for your reply!

I'm trying to train a object detection dataset/model MobileNetSSDv2,  I'm using for the oak1 and raspberry pi3 as the hoist.  i need speed over accuracy as the oak will being moving slowly while detecting.  I collected my images using the oak at 300x300
Thanks
Adam

**Comment by Luxonis-Brandon** [comment]
Thanks.  Yes, we can help more directly while we transition.  Would you mind shooting us an email at brandon at luxonis dot come with support@luxonis.com CCed.

We can provide some pointers offline during this transitionary period.

Thanks,
Brandon
