### ISSUE TITLE
Several Dependency Conflicts on YOLOv6n training notebook.

### ISSUE THREAD

**Issue by dhartness** [luxonis/depthai-ml-training#36]
![yolov6n_dependencies](https://user-images.githubusercontent.com/91334435/211334211-7a63bb60-d496-45fb-8cdb-692721f96b6a.jpg)

Hi, I ran into these dependency conflicts last week, along with the "numpy has no attribute 'int'" and worked through them. I don't know if its worth it to update the Colab notebook as these things continue to change but this install string resolved the issue. A lot of it was specifying the highest levels without going over routine.

`!pip install -U -q torch==1.13.0 torchvision>=0.9.0 protobuf==3.19.5 numpy==1.23.1 opencv-python>=4.1.2 PyYAML>=5.3.1 scipy>=1.4.1 tqdm>=4.41.0 addict>=2.4.0 tensorboard==2.9.0 pycocotools>=2.0 onnx>=1.10.0 onnx-simplifier>=0.3.6 thop`

Thank you guys for all of the hard work you've put into this, though. 👍 It must be a mess keeping all of these code iterations together.

**Comment by dhartness** [comment]
Had to update it again today:
`!pip install -U -q torch>=1.13.0 torchvision>=0.9.0 protobuf==3.19.5 numpy==1.23.1 opencv-python>=4.1.2 PyYAML>=5.3.1 scipy>=1.4.1 tqdm>=4.41.0 addict>=2.4.0 tensorboard==2.9.0 pycocotools>=2.0 onnx>=1.10.0 onnx-simplifier>=0.3.6 jedi>=0.10 thop`

Maybe just 'jedi' alone would have resolved the issue without changing 'torch' and 'torchvision' but this worked.

**Comment by tersekmatija** [comment]
Hi @dhartness, thanks for reporting this! @HonzaCuhel do you mind updating the notebook?

**Comment by HonzaCuhel** [comment]
@tersekmatija, sure, I'll update it.
@dhartness thank you very much for noticing!

**Comment by HonzaCuhel** [comment]
The dependencies are now updated!

Again, thank you very much, @dhartness!
