### ISSUE TITLE
Yolov7 issue

### ISSUE THREAD

**Issue by RarimanRocha** [luxonis/depthai-ml-training#43]
Hello 
When I try to execute the tensorboard cell or start traing I get the following error on Yolov7 notebook 

tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA

 If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

**Comment by tersekmatija** [comment]
Hey @RarimanRocha , thanks for reporting the issue. Are you using Google Colab?

I assume it is related to dependencies. Do you mind calling `!pip install protobuf==3.20` at the top of the notebook? CC @HonzaCuhel to look into this further.

**Comment by RarimanRocha** [comment]
Hello, I am using Google Colab.

I called !pip install protobuf==3.20, and the code is working. Thanks

**Comment by tersekmatija** [comment]
Great to know @RarimanRocha . CC @HonzaCuhel on updating the requirements :)

**Comment by HonzaCuhel** [comment]
@RarimanRocha thank you very much for noticing!

@tersekmatija Already updated and created a [PR](https://github.com/luxonis/depthai-ml-training/pull/44).
