### ISSUE TITLE
Error when running main.py device-decoding

### ISSUE THREAD

**Issue by Mario-arinapin** [luxonis/depthai-ml-training#46]
Hello! 

I was trying to follow the step within the YOLOv8 colab and found an error in the final steps, when trying to run the camera with the obtained model. 

Likewise, the same happened when I tried to run the Yolov7 object detection colab. Here is the error trace. 

/home/venv/lib/python3.9/site-packages/depthai_sdk/oak_camera.py:237: UsbWarning: Device connected in USB2 mode! This might cause some issues. In such case, please try using a (different) USB3 cable, or force USB2 mode 'with OakCamera(usbSpeed=depthai.UsbSpeed.HIGH)'
  warnings.warn("Device connected in USB2 mode! This might cause some issues. "

Downloading /home/user/.cache/blobconverter/bestyolo7_openvino_2021.4_6shave.blob...
{
    "exit_code": 1,
    "message": "Command failed with exit code 1, command: /opt/intel/openvino2021_4/deployment_tools/inference_engine/lib/intel64/myriad_compile -m /tmp/blobconverter/0894b1b8dea94e2f8efe44cf49f13736/bestyolo7/FP16/bestyolo7.xml -o /tmp/blobconverter/0894b1b8dea94e2f8efe44cf49f13736/bestyolo7/FP16/bestyolo7.blob -c /tmp/blobconverter/0894b1b8dea94e2f8efe44cf49f13736/myriad_compile_config.txt -ip U8",
    "stderr": "Unknown model format! Cannot find reader for model format: xml and read the model: /tmp/blobconverter/0894b1b8dea94e2f8efe44cf49f13736/bestyolo7/FP16/bestyolo7.xml. Please check that reader library exists in your PATH.\n",
    "stdout": "Inference Engine: \n\tIE version ......... 2021.4.2\n\tBuild ........... 2021.4.2-3974-e2a469a3450-releases/2021/4\n"
}
Closing OAK camera

Any ideas what might be causing this issue?

**Comment by Mario-arinapin** [comment]
Sure, I zipped them here [bestyolo7xmlandbin.zip](https://github.com/luxonis/depthai-ml-training/files/10999098/bestyolo7xmlandbin.zip)
Thanks

**Comment by Erol444** [comment]
Hi @Mario-arinapin , yes, very well could be.. Blobconverter is just a simple wrapper around openvino tools, which is also causing the crash (looking error code above).

**Comment by Mario-arinapin** [comment]
Appreciate the help, thank you.
