### ISSUE TITLE
Conversion issue

### ISSUE THREAD

**Issue by martin0496** [luxonis/depthai-ml-training#50]
https://colab.research.google.com/drive/1oNxfvx5jOfcmk1Nx0qavjLN8KtWcLRn6?usp=sharing#scrollTo=b5Z1QFooGIW8

Hi 
I am working on this project and I want to test it. The code works fine until the conversion starts. I receive multiple errors. 
Can you please help with this and try to check the code ?

Thank you very much

**Comment by Erol444** [comment]
@tersekmatija @HonzaCuhel do we have any working classification notebook?

**Comment by martin0496** [comment]
Thank you very much for all your support and guidance

**Comment by HonzaCuhel** [comment]
Hi @martin0496,

I'll look into it. Did it work for you last week?

Best,
Jan

**Comment by martin0496** [comment]
@HonzaCuhel 

I tried it for the first time today. 
When I run the mo command it was not found that is why i installed openvino-dev using pip. After some research i found that the problem is related to versions. how can I solve it and make it run to achieve the final blob model ? 
Thank you very much for the support

**Comment by martin0496** [comment]
@HonzaCuhel 


if we are installing a specific version of openvino to do the conversion, why we use the !mo command ? 
because when I try to run it, the error is " mo command not found" 

I will be very grateful if you can check the conversion part. THank you very much for all your support and guidance

**Comment by tersekmatija** [comment]
Hey @martin0496 , can you give [this notebook](https://colab.research.google.com/drive/18qHjSV1jkfFQHcgnDIM5dJzkHiP00AwT?usp=sharing) a try? Note you will have to restart the runtime after the first 2 packages get installed. Let me know if this works.

**Comment by martin0496** [comment]
@HonzaCuhel @tersekmatija 

Thank you very much. The conversion works fine and the final format is correct. Great Tutorial!

**Comment by HonzaCuhel** [comment]
@martin0496 I am glad to hear that we were able to solve the issue!
