### ISSUE TITLE
Add postprocessing in OAK-d-PoE

### ISSUE THREAD

**Issue by ilyagasan** [luxonis/depthai-ml-training#61]
Hello!

I am working with the OAK-D-PoE camera. Currently, I have successfully integrated the YOLO v7 neural network into this camera using the tutorial provided on GitHub (https://github.com/luxonis/depthai-experiments/tree/769029ea4e215d03f741bcf085d1bb6c94009856/gen2-yolo/device-decoding).

Could you please advise if it's possible to add post-processing directly to the camera, so that neural network processing -> post-processing -> data transmission to the computer occurs within the camera itself?

I would greatly appreciate your response and any advice on how to accomplish this.

Thank you in advance for your assistance.

**Comment by tersekmatija** [comment]
> Hello!
> 
> I am working with the OAK-D-PoE camera. Currently, I have successfully integrated the YOLO v7 neural network into this camera using the tutorial provided on GitHub (https://github.com/luxonis/depthai-experiments/tree/769029ea4e215d03f741bcf085d1bb6c94009856/gen2-yolo/device-decoding).
> 
> Could you please advise if it's possible to add post-processing directly to the camera, so that neural network processing -> post-processing -> data transmission to the computer occurs within the camera itself?
> 
> I would greatly appreciate your response and any advice on how to accomplish this.
> 
> Thank you in advance for your assistance.

Hey @ilyagasan ,

Could you explain what you mean please? The main_api.py in the device-decoding performs all of the decoding on the camera itself, the only part that happens offline (on computer) is the visualization of ImgDetections.

**Comment by ilyagasan** [comment]
Yes, you are absolutely right, the YOLOv7 model operates entirely on the camera side. However, I have developed a function for calculating the volume of an object based on the bounding box (bbox). The question is whether it is possible to integrate my function into the pipeline so that it also runs on the camera.

**Comment by tersekmatija** [comment]
If your script is Python only (no external libraries), you could use [ScriptNode](https://docs.luxonis.com/projects/api/en/latest/components/nodes/script/) after the YoloDetectionNetwork in the pipeline. The code inside the ScriptNode would execute fully on device.

**Comment by IlyaGasanPetrGY** [comment]
> If your script is Python only (no external libraries), you could use [ScriptNode](https://docs.luxonis.com/projects/api/en/latest/components/nodes/script/) after the YoloDetectionNetwork in the pipeline. The code inside the ScriptNode would execute fully on device. 

Thank you, but if I don't need to use opencv and anadize the image, then I need to do it. Thanks again very much!

**Comment by IlyaGasanPetrGY** [comment]
Necessary
