### ISSUE TITLE
YOLOv4-tiny custom - no detection

### ISSUE THREAD

**Issue by Whisper94** [luxonis/depthai-ml-training#9]
After custom training and tried to run blob file with OAK-D WiFi but there is no detections.
Could you explain what I've done wrong? the converted blob file I placed in nn folder. Change all labels in Python Script according docu. Also tried to reduce IoU and threshold to 0.1 but there is no detection. With colab test yolov4-tiny works fine. OpenVino convertingI couldn't verify (newby)
In tutorials I've found different versions of OpenVINO (2021_1 and 2021_2). For my tests I use 2021_1 because I couldn't find how to download with wget the version from februar or march.
I've tried two different example scripts (from colab notebook and from docu)
I have:
- 2 classes
- 608x608 Yolov4-tiny
- placed only .blob file without any other files during converting

Could you help me to solve my issue.
Thank you! 
And it were very great if you could provide me a link with actual documentation, because many hyperlinks are "dead"

**Comment by Erol444** [comment]
Hello @Whisper94 ,
I would like to apologize for the un-updated colab notebooks that have dead links and old openvino versions. We actually just updated all the notebooks in this PR https://github.com/luxonis/depthai-ml-training/pull/8. I believe Lukasz tested all the notebooks so they are working as expected and wrote instructions on how to run the blobs on the depthAI. You should check the PR branch for more info and follow those notebooks. I am sorry about the inconvenience.
Thanks, Erik

**Comment by Whisper94** [comment]
Thank you Erik for fast answer.
I don't know what I did wrong but actual I'm confused because everything what I tried, every tutorial what I read has no success. Also default model tiny-yolo-v3 has NO detection but in console is another output. Yesterday I've tried it with blob converter but the same as earlier -> nothing happens. OpenVINO version is probably doesn't matter if they are match with blob file and script.

If I try my model with `python depthai_demo.py -cnn custom_model_folder_under_nn --cnn_input_size 608x608` there is no results but this is output from console:
![image](https://user-images.githubusercontent.com/60612672/120650457-1ad4a900-c47e-11eb-8dc8-247ea101a58e.png)
my converted blob files looks like "yolov4-tiny_custom_openvino_2021.3_5shave.blob". From tutorials I've changed JSON file, renamed it to like a blob file and put them in the same folder:
![image](https://user-images.githubusercontent.com/60612672/120653086-aa7b5700-c480-11eb-827e-d117cc303411.png)

`{
    "nn_config":
    {
        "output_format" : "detection",
        "NN_family" : "YOLO",
        "input_size": "608x608",
        "NN_specific_metadata" :
        { 
            "classes" : 2,
            "coordinates" : 4,
            "anchors" : [10,14, 23,27, 37,58, 81,82, 135,169, 344,319],
            "anchor_masks" : 
            {
                "side26" : [1,2,3],
                "side13" : [3,4,5]
            },
            "iou_threshold" : 0.5,
            "confidence_threshold" : 0.1
        }
    },
    "mappings":
    {
        "labels":
        [
            "1",
			"2"
        ]
    }
}

`
however it doesn't work and I'm at the moment frustrated that simple things don't work as a should! Also the default version looks like with a bug or issue with my device?

with default parameters from tiny-yolo-v3 `python depthai_demo.py -cnn tiny-yolo-v3` there is something with wrong CNN input size. But I don't know which HxW it was trained and where is it stored
![image](https://user-images.githubusercontent.com/60612672/120650935-86b71180-c47e-11eb-8d12-77dc039b55e3.png)


I find ever different versions:
https://docs.luxonis.com/en/latest/pages/tutorials/first_steps/#using-custom-models
https://blog.roboflow.com/deploy-luxonis-oak/
https://colab.research.google.com/github/luxonis/depthai-ml-training/blob/use_blobconverter/colab-notebooks/Easy_TinyYOLOv4_Object_Detector_Training_on_Custom_Data.ipynb
https://colab.research.google.com/github/luxonis/depthai-ml-training/blob/master/colab-notebooks/Easy_TinyYOLOv4_Object_Detector_Training_on_Custom_Data.ipynb

Could you tell me what is wrong or provide me how can tell me it? Probably you need more information, let me know. At the moment I was only trying with default setting to be sure that everything works well but it isn't...

**Comment by Erol444** [comment]
Hello @Whisper94,
I apologize for your dissatisfaction with the UX of the DepthAI. We are actively trying to improve it and resolve all the bugs as fast as possible. One example, as you mentioned, is the incorrect `tiny-yolo-v3` size in the `depthai_demo.py`. We just merged the PR (https://github.com/luxonis/depthai/pull/392) so it is fixed now.
For training, we advise you to use [Roboflow](https://roboflow.com/), as it removed tons of complicated steps - steps where one can lose a lot of time, especially if it's the first time training. They even have an article about deploying the model to OAK-D, as you pointed out.
Our training examples are for users that want more customizability. And we have just updated all the notebooks with the PR I mentioned above.
If something isn't working as expected in the `depthai` repo, you can either open an issue on that repo or ask for help on our discord server - for an easier communication.
Thanks, Erik
